name: Release Task

on:
  push:
    tags:
      # The regex support here is limited, so just match everything that starts with llvmorg- and filter later.
      - 'llvmorg-*'

jobs:
  release-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Tag
        id: validate-tag
        run: |
          test "${{ github.actor }}" = "tstellar" || test "${{ github.actor }}" = "tru"
          echo "${{ github.ref_name }}" | grep -e '^llvmorg-[0-9]\+\.[0-9]\+\.[0-9]\+\(-rc[0-9]\+\)\?$'
          release_version=$(echo "${{ github.ref_name }}" | sed 's/llvmorg-//g')
          echo "release-version=$release_version" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: |
          sudo apt-get install -y \
              doxygen \
              graphviz \
              python3-github \
              python3-recommonmark \
              python3-sphinx \
              ninja-build \
              texlive-font-utils
          pip3 install --user sphinx-markdown-tables

      - name: Checkout LLVM
        uses: actions/checkout@v3

      - name: Create Release
        run: |
          ./llvm/utils/release/./github-upload-release.py --token ${{ github.token }} --release ${{ steps.validate-tag.outputs.release-version }} create
